server:
  port: 8080
spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
    #username: sa
    #password:
    url: jdbc:mysql://localhost:3306/als?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: arpi
    password: code1234!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.H2Dialect
        dialect: org.hibernate.dialect.MySQL8Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: false
    locations: classpath:db/migration
logging:
  level:
    org.hibernate.type.descriptor.sql: trace